config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'bootstrap', to: 'bootstrap#index'
  get 'tachyons',  to: 'tachyons#index'

  get '*path', to: 'home#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bootstrap_controller.rb
class BootstrapController < ApplicationController

  layout 'bootstrap'

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/tachyons_controller.rb
class TachyonsController < ApplicationController

  layout 'tachyons'

  def index
  end
end

app/views/home/index.html.erb
<h1>ToDo list powered by Opal-Ferro</h1>
<br/>
<%= link_to('Bootstrap version', bootstrap_path) %>
<br/>
<br/>
<br/>
<%= link_to('Tachyons version', tachyons_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo list powered by Opal-Ferro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="description", content="ToDo list powered by Opal-Ferro">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/favicon.ico', type: 'image/ico' %>
  </head>
  <body>
    <div style="margin: 3em 0 0 3em">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo list powered by Opal-Ferro and Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="description", content="ToDo list powered by Opal-Ferro and Bootstrap">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/favicon.ico', type: 'image/ico' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css', integrity: 'sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB', crossorigin: 'anonymous' %>
    <%= javascript_include_tag 'bootstrap' %>
  </head>
  <body/>
</html>

app/views/layouts/tachyons.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo list powered by Opal-Ferro and Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="description", content="ToDo list powered by Opal-Ferro and Bootstrap">
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/favicon.ico', type: 'image/ico' %>
    <%= stylesheet_link_tag    'https://unpkg.com/tachyons@4.9.1/css/tachyons.min.css' %>
    <%= javascript_include_tag 'tachyons' %>
  </head>
  <body/>
</html>